### ISSUE TITLE
No crates actually released

### ISSUE THREAD

**Issue by matthiasbeyer** [neithernut/git-dit#122]
As far as I can see, none of our versions (neither 0.2.0 nor 0.2.1) is released: https://crates.io/search?q=git-dit

**Comment by neithernut** [comment]
I can't currently publish the crate on this machine due to an old version of rust being installed (`1.16`). I will certainly not publish the crate with the work-around currently in place on my local machine and I can't update since newer versions don't yet show up in the package repos (because of reasons). Maybe I'll do a rogue install of `rust`, but I really don't want to, at least right now.

You may publish the library as well, if you can spare the time (and resources). However, you'll not be able to publish the binary because we don't specify the `libgitdit`-version the binary depends on. We should have bumped/set it during the release preparations for `0.2.0` and `0.2.1` (I'll try to keep that in mind for upcoming releases). Honestly, I don't see the point in publishing a binary via [crates.io](https://crates.io), anyway.

**Comment by neithernut** [comment]
Feel free to remove the assignment again if you don't feel like publishing or don't have the resources right now, @matthiasbeyer.

I just realized that I could also install newer versions of rust through an overlay. Maybe I'll do that tomorrow.

**Comment by matthiasbeyer** [comment]
Closing this. See #123
